### ISSUE TITLE
ComputeServer Groups

### ISSUE THREAD

**Issue by kaush** [gomorpheus/morpheus-plugin-core#19]
I am creating ComputeServers (Hosts and VM types) through the cloud plugin. I want to create (if not present) Groups per site/location and assign them to ComputeServers. I tried setting provisionSiteId [to the id from compute_site] but that didn't work. Bob Whiton suggested: "We need to create ComputeSites via the plugin for this and we currently do not expose a context to do this"

Is this something that can be easily implemented? We are going to have 1000s of edge sites and this is very important to group them per site and have the search/filter capability for the same.

ref: Support Ticket #66441

**Comment by davydotcom** [comment]
Its important to note servers dont belong to groups. the provisionSiteId is just a reference for when the server is created as part of an add instance request.

**Comment by davydotcom** [comment]
If you are wanting to organize the servers on the edge sites im betting in MaaS you want to use the ComputeZonePools

**Comment by kaush** [comment]
Thanks for the update [davydotcom](https://github.com/davydotcom).
I don't see how ComputeZonePools will give tenants the ability to put/see the CoputeServers (Infrastructure>Hosts|Virtual Machines) into different sites/groups. From some sample code I saw the ability for Instances to achieve this but not for Hosts.
