### ISSUE TITLE
Amend docs - Task plugin image format support SVG?

### ISSUE THREAD

**Issue by olliephillips** [gomorpheus/morpheus-plugin-core#21]
I could not get PNG images displaying for a custom task plugin. I **think** the requirement has changed and later Morpheus plugin framework versions now expects SVG? When i tried SVG it worked first time as expected. I am using 0.13.1.

I'd be very happy to amend the docs and send a PR but wanted to confirm it was the case before doing so.

The docs state PNG [here](https://github.com/gomorpheus/morpheus-plugin-core/blob/v0.12.x/morpheus-plugin-docs/src/docs/asciidoc/TaskPlugin.adoc#task-logo).

**Comment by davydotcom** [comment]
It should support both. There is some cleanup going on there with a new Icon object that lets you specify it rather than infer the image path from code.
