### ISSUE TITLE
[QUESTION] How to check number of AWS clouds in a sub-tenant from a UI plugin?

### ISSUE THREAD

**Issue by nickswekosky-lumen** [gomorpheus/morpheus-plugin-core#23]
This is a follow up from Morpheus case 67928. I'm submitting a question/issue based on feedback from Evan.

As a developer that's building a UI plugin, I would like to create conditional UI logic based on if an AWS cloud is created or not. I've been told it's not possible to query the API because there's no way to get the correct credentials/token for that user or that sub-tenant. In addition, I'm told the plugin framework allows you to access some of the data that you would get from API calls by using the morpheus context, but I'm not a developer so I'm not certain if this is true.

If I'm building a UI plugin, how can I programmatically check the number of AWS clouds in my sub-tenant environment?

Please let me know if you have any questions. Thank you!

**Comment by davydotcom** [comment]
This is documented in the java api doc. 

"but I'm not a developer " in regards to this comment it is highly recommended a developer make these plugins. They are not designed to be no code plugins.

There is not currently a method to list clouds by a filter in the MorpheusCloudService . However this could be queried directly in the database by using the readOnlyDatabaseConnection . An example of this being used is in the sample report type plugin but could be used anywhere.  You would need to query the compute_zone and compute_zone_type tables

**Comment by nickswekosky-lumen** [comment]
Thanks @davydotcom. While I'm not currently an engineer, I'm a former engineer so no worries with respect to the no-code capabilities.

I'm told the Morpheus context has a method called `getApplicationToken` that can be used to query the Morpheus API from the context of a sub-tenant user to list the clouds and check for AWS clouds by cloud type. Is that true?

I ask because our dev told me that, but I don't see that in [MorpheusContext.java](https://github.com/gomorpheus/morpheus-plugin-core/blob/v0.12.x/morpheus-plugin-api/src/main/java/com/morpheusdata/core/MorpheusContext.java).

If that method is available, do you still recommend querying the database over calling the API?

Please lmk if you have any questions. Thanks!

**Comment by davydotcom** [comment]
I dont recommend doing that. I think what needs to happen is i need to expose the api query for you in the CloudService on the next release cycle. I have it in my notes to do for 5.5.2 will this work for you?

**Comment by nickswekosky-lumen** [comment]
That does seem like the ideal experience, @davydotcom. Please let me know if there's any way I can be helpful.

May I ask why you don't recommend the other approach?

**Comment by davydotcom** [comment]
Dataservices have since been added that allow querying the database more freely, closing
